# Generated by Django 5.0.6 on 2026-07-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMetric',
            fields=[
                ('course_id', models.UUIDField(primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField()),
                ('enrollment_count', models.IntegerField(default=0)),
                ('completion_count', models.IntegerField(default=0)),
                ('score_sum', models.IntegerField(default=0)),
                ('score_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('organization_id', models.UUIDField()),
                ('new_users', models.IntegerField(default=0)),
                ('enrollments', models.IntegerField(default=0)),
                ('certificates_issued', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('date', 'organization_id')},
            },
        ),
    ]
