# Generated by Django 5.0.6 on 2026-07-22 20:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploader_id', models.UUIDField()),
                ('organization_id', models.UUIDField(blank=True, null=True)),
                ('url', models.URLField(max_length=500)),
                ('content_type', models.CharField(max_length=100)),
                ('original_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
